### ISSUE TITLE
Own Your Swarm

### ISSUE THREAD

**Issue by bmann** [bmann/microglue#10]
Like OwnYourGram, this is an indieweb / micropublish connector for Swarm / Foursquare.

**Comment by bmann** [comment]
Example post

Comes across as an hcard. Need to edit my template to detect Swarm YAML. 

```
---
layout: single
date: '2018-10-12T15:46:10.000Z'
title: ''
mf-syndication:
  - 'https://www.swarmapp.com/user/39650/checkin/5bc0c1c275dcb7002c154511'
mf-photo:
  - >-
    https://igx.4sqi.net/img/general/original/39650_qoDzzDRQyYTnE_nTa3AMZ7YsP_u-p4_7jJWNHSKPO-M.jpg
mf-checkin:
  - type:
      - h-card
    properties:
      name:
        - Laughing Bean Coffee
      url:
        - 'https://foursquare.com/v/4acfc331f964a520d0d520e3'
      latitude:
        - 49.28135734097561
      longitude:
        - -123.04954218818958
      street-address:
        - 2695 E Hastings St.
      locality:
        - Vancouver
      region:
        - BC
      country-name:
        - Canada
    value: 'https://foursquare.com/v/4acfc331f964a520d0d520e3'
mf-location:
  - type:
      - h-adr
    properties:
      latitude:
        - 49.28135734097561
      longitude:
        - -123.04954218818958
      street-address:
        - 2695 E Hastings St.
      locality:
        - Vancouver
      region:
        - BC
      country-name:
        - Canada
slug: '56770'
category: social
---
Super fun local community coffee place. Road trip begins!

```
